name: GitHub Snake

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate GitHub Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            snake/github-snake.svg
            snake/github-snake-dark.svg?palette=github-dark
            snake/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: List files in dist directory
        run: ls -l snake/

      - name: Commit and push generated files
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          message: "Add generated GitHub Snake images"
          add: "snake/*"
